name = "statistic-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "statistic-db"
database_id = "f9ca5a47-5d07-4c42-8047-e9d23a9e48be"

[vars]
JWT_SECRET = "change-me-in-production"
